In [1]:
import numpy as np

In [2]:
a = np.array([1])

In [3]:
a.ndim

1

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a.ndim

1

In [6]:
b = np.array(2)

In [7]:
b.ndim

0

In [8]:
c = np.array([[2,3],[5,6]])
c.ndim

2

In [23]:
d = np.array([[1,2,4],
              [3,5,2],
              [3,4,5]])
print(d.ndim)
print(d.shape)

2
(3, 3)


In [27]:
d = np.array([[1,2],
              [3,2],
              [4,5]])
print(d.ndim)
print(d.shape)

2
(3, 2)


In [29]:
d.shape = (2,3)
print(d)
print(d.shape)

[[1 2 3]
 [2 4 5]]
(2, 3)


In [25]:
d1 = d.reshape(2,3)
print(d1)
print(d1.shape)

[[1 2 3]
 [2 4 5]]
(2, 3)


In [11]:
e = np.array([[[1,2,4],
              [3,5,2],
              [3,4,5]],
             [[0,1,4],
              [3,6,2],
              [3,2,6]]])
e.ndim

3

In [13]:
a1 = np.array([1,2,3,4,6], ndmin=2)

In [15]:
print(a1)
print(a1.ndim)

[[1 2 3 4 6]]
2


In [16]:
a1.dtype

dtype('int32')

In [17]:
a1 = np.array([1,2,3,4,6], ndmin=2, dtype=np.float32)

In [18]:
print(a1.dtype)

float32


In [22]:
a1.shape

(5,)

In [19]:
a1 = np.array([1,2,3,4,6], ndmin=1, dtype=complex)

In [20]:
print(a1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 6.+0.j]


In [21]:
a1.shape

(5,)

In [30]:
d = np.array([[1,2],
              [3,2],
              [4,5]])
print(d.ndim)
print(d.shape)

2
(3, 2)


In [32]:
d.transpose()

array([[1, 3, 4],
       [2, 2, 5]])

In [33]:
np.zeros(5, dtype=np.int64)

array([0, 0, 0, 0, 0], dtype=int64)

In [34]:
np.zeros((3,5), dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [35]:
np.ones((3,5), dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [36]:
np.full((3,5), 6, dtype=np.int64)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int64)

In [ ]:
y = mx + c
[y1, x1],
[y2, x2],
[y3, x3]

m, c



In [42]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
np.eye(6).ndim

2

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [45]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(3,6,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5])

In [48]:
np.linspace(2, 3, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [49]:
np.linspace(2, 3, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [52]:
np.linspace(0, 100, num=10, endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [53]:
m = np.array([[2,3,4],[9, 1, 5]])
print(m)

[[2 3 4]
 [9 1 5]]


In [57]:
print(m.min(), m.max(), m.mean())

1 9 4.0


In [58]:
m1 = np.array([[2, 3, 4, 23, 44, 78],[67, 89, 7, 8, 1, 5]])
print(m1)

[[ 2  3  4 23 44 78]
 [67 89  7  8  1  5]]


In [61]:
m1.argmin(axis = 0)

array([0, 0, 0, 1, 1, 1], dtype=int64)

In [62]:
m1.argmin(axis = 1)

array([0, 4], dtype=int64)

In [63]:
m1.argmax(axis = 1)

array([5, 1], dtype=int64)

In [68]:
np.percentile(m1,100)

89.0

In [67]:
m1.mean()

27.583333333333332

In [69]:
dir(m1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [70]:
m1.flatten()

array([ 2,  3,  4, 23, 44, 78, 67, 89,  7,  8,  1,  5])

In [71]:
m1

array([[ 2,  3,  4, 23, 44, 78],
       [67, 89,  7,  8,  1,  5]])

In [72]:
n1 = m1.flatten()
n1.reshape(2,6)

array([[ 2,  3,  4, 23, 44, 78],
       [67, 89,  7,  8,  1,  5]])

In [74]:
print(m1)

[[ 2  3  4 23 44 78]
 [67 89  7  8  1  5]]


In [79]:
# cumsum

# Monthly results 
%time
a = np.array([[3, 4, 4], [2, 4, 6], [5, 1, -8], [7, 9, 3]])
print(a.cumsum())

Wall time: 0 ns
[ 3  7 11 13 17 23 28 29 21 28 37 40]


In [103]:
# Old approach
a = np.array([[3, 4, 4], [2, 4, 6], [5, 1, -8], [7, 9, 3]])
b = a.flatten()
c = []

sum = 0
for i in b:
  sum = sum + i
  c.append(sum)

d = np.array(c)
print(d, type(d))


[ 3  7 11 13 17 23 28 29 21 28 37 40] <class 'numpy.ndarray'>


In [91]:
a.size

12